<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'content' => '',
    'cat_name' => '激情美图',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'mt',
    'moban' => 'article_cat_mt',
    'smallmoban' => 'article_mt',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '2',
    'content' => '',
    'cat_name' => '性感美女',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'define_url' => 'xgmn',
    'moban' => 'article_cat_tk',
    'smallmoban' => 'article_mt',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  2 => 
  array (
    'cat_id' => '3',
    'content' => '',
    'cat_name' => '丝袜美腿',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'define_url' => 'xwmt',
    'moban' => 'article_cat_tk',
    'smallmoban' => 'article_mt',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
);
?>