<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '亚洲经典',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 0,
    'id' => '1',
    'name' => '亚洲经典',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '欧美经典',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '2',
    'name' => '欧美经典',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '唯美短片',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '唯美短片',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '情趣诱惑',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '情趣诱惑',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '制服丝袜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '制服丝袜',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '热门自拍',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '热门自拍',
  ),
);
?>